[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/personnes/lili-jeanne-flourez/index.html"
to = "/portraits/lili-jeanne-flourez/"

[[redirects]]
from = "/personnes/categories/equipe/index.html"
to = "/portraits/categories/equipe/"

[[redirects]]
from = "/personnes/categories/portrait/index.html"
to = "/portraits/categories/portrait/"

[[redirects]]
from = "/personnes/index.html"
to = "/portraits/"

[[redirects]]
from = "/organisations/index.html"
to = "/structures/"

[[redirects]]
from = "/equipe/index.html"
to = "/portraits/"

[[redirects]]
from = "/personnes/beatrice/index.html"
to = "/portraits/beatrice/"

[[redirects]]
from = "/organisations-1/index.html"
to = "/actualites/"

[[redirects]]
from = "/equipe/noe-blanquart/index.html"
to = "/portraits/noe-blanquart/"

[[redirects]]
from = "/ressources/index.html"
to = "/actualites/"

[[redirects]]
from = "/projet/index.html"
to = "/a-propos/"

[[redirects]]
from = "/personnes/noe-blanquart/index.html"
to = "/portraits/noe-blanquart/"

[[redirects]]
from = "/equipe/lili-jeanne-flourez/index.html"
to = "/portraits/lili-jeanne-flourez/"

[[redirects]]
from = "/equipe/categories/equipe/index.html"
to = "/portraits/categories/equipe/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/equipe-editoriale/"

